try {
    throw "oops";
} catch e {
    print( "caught", e);
}
